### ISSUE TITLE
CPU speed inconsistent

### ISSUE THREAD

**Issue by pjmi1** [AlexGoodyear/agoodWatch#11]
The CPU speed shown in the "About" display seems inconsistent - mostly showing highest speed 240 MHz (ie also high energy use).

What is the designed behaviour for CPU speed? I'd have thought it should run at low speed apart from when updating animations, then quickly timing-out to become slow speed, and the About screen should re-draw when the speed changes, to show that change.

Thanks for sharing your code.

**Comment by AlexGoodyear** [comment]
The CPU speed is correct and does alter depending upon which watch face you have set to be the default. The default watch face is updated even if you are looking at another screen. This avoids the watch face displaying an old time when you return to it after navigating through the other screens. The graphical/animated faces require significant CPU resource. The CPU frequency is reduced when the watch sleeps but has little effect because the CPU is suspended anyway.
